// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjAgoUez4W5Rjy96Tiuy_kHIRXcQzXTNg',
    appId: '1:431463946737:web:1601932d58892453d00c50',
    messagingSenderId: '431463946737',
    projectId: 'project-01-ab6ab',
    authDomain: 'project-01-ab6ab.firebaseapp.com',
    storageBucket: 'project-01-ab6ab.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQq2wYLh4gJf2gG6RQ15YsNL93r2lbvMU',
    appId: '1:431463946737:ios:6f4931a5511f8f6ed00c50',
    messagingSenderId: '431463946737',
    projectId: 'project-01-ab6ab',
    storageBucket: 'project-01-ab6ab.appspot.com',
    androidClientId: '431463946737-epj4nq9vlgvgn1reo14v0d1bov5sn002.apps.googleusercontent.com',
    iosClientId: '431463946737-k1chong625ohuk353g5o8499cci65jdq.apps.googleusercontent.com',
    iosBundleId: 'com.example.doctorApp.RunnerTests',
  );
}
